name: Deploy para Hostinger

on:
  push:
    branches:
      - main # Quando houver push para a branch main, a automação executa

jobs:
  web-deploy:
    name: 🎉 Deploy Hostinger
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Baixando os arquivos
        uses: actions/checkout@v4
      
      - name: 🛠️ Instalando o Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: 📦 Instalando dependências
        run: npm ci
        
      - name: 🏗️ Construindo o projeto
        run: npm run build
        
      - name: 🚀 Enviando para a Hostinger via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/
          local-dir: ./dist/
