name: Deploy para Napoleon

on:
  push:
    branches:
      - main # Quando houver push para a branch main, a automação executa

jobs:
  web-deploy:
    name: 🚀 Deploy Napoleon (SFTP)
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 🚚 Baixando os arquivos
        uses: actions/checkout@v4

      - name: 🛠️ Instalando o Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: 📦 Instalando dependências
        run: npm ci

      - name: 🏗️ Construindo o projeto
        run: npm run build

      - name: 🚀 Enviando para a Napoleon via SFTP
        uses: milanmk/actions-file-deployer@master
        with:
          remote-host: ${{ secrets.FTP_SERVER }}
          remote-protocol: sftp
          remote-port: 1157
          remote-user: ${{ secrets.FTP_USERNAME }}
          remote-password: ${{ secrets.FTP_PASSWORD }}
          remote-path: /domains/trglogistics.com.br/public_html/
          local-path: ./dist/
          sync: full


